services:
  nexusgate:
    image: ghcr.io/2540587868/nexusgate:latest
    ports:
      - "9090:9090"
      - "9443:8443"
      - "9091:9091"
      - "9092:9092"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./config:/etc/nexusgate:ro
    restart: unless-stopped
